version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
  kafka:
     image: wurstmeister/kafka
     container_name: kafka
     ports:
       - "9092:9092"
     environment:
       KAFKA_ADVERTISED_HOST_NAME: kafka
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_CREATE_TOPICS: "instance-info:1:1"
     restart: unless-stopped
     
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: "random-secret"
    restart: unless-stopped
  kafka-producer:
    image: kafkaproducer:latest
    build:
      context: producer
      dockerfile: Dockerfile
    container_name: kafka-producer
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_HOSTS: kafka:9092
      KAFKA_TOPIC: instance-info
    depends_on:
      - zookeeper
      - kafka
    restart: always
  # kafka-consumer:
  #   image: kafkaconsumer:latest
  #   build:
  #     context: consumer
  #     dockerfile: Dockerfile
  #   container_name: kafka-consumer
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #     KAFKA_HOSTS: kafka:9092
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #     - kafka-producer
  #   restart: always
